### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by BTRLabs** [sbooth/AudioXCFrameworks#41]
As of today with XCode 14.0.1 installed, doing the following (as instructed per the readme.md file's "Building" section) results in compilations issues due to missing files (primarily *.h files).  What am I missing?

git clone git@github.com:sbooth/AudioXCFrameworks.git
cd AudioXCFrameworks
make

Thanks for your response and for putting this collection together to begin with!

**Comment by sbooth** [comment]
The `config.h` file in the `flac-src` directory was inadvertently omitted because it is included in the FLAC project's `.gitignore`.

**Comment by sbooth** [comment]
There appear to be some other minor issues with conflicting scheme names as well.

**Comment by sbooth** [comment]
Could you try the `compilation-errors` branch and see if that works for you? It compiles with no errors for me.

**Comment by BTRLabs** [comment]
The `compilation-errors` branch compiled without issue for me.  Thanks for the prompt response!
