### ISSUE TITLE
Breaks when trying to archive

### ISSUE THREAD

**Issue by dylancom** [sbooth/AudioXCFrameworks#7]
I used this to make an xcframework for Taglib. It works fine when I use the .xcframework on a simulator (debug).
When I'm trying to create an archive (release) it brings up the following warning: `ignoring file ***/frameworks/taglib.xcframework/ios-arm64/taglib.framework/taglib, building for iOS-armv7 but attempting to link with file built for iOS-arm64`
So it doesn't load Taglib (on release) which results in all kinds of "undefined symbol: TagLib::Ogg" errors.

**Comment by sbooth** [comment]
Is your target built for armv7? If so, the xcframework is only built for arm64.

**Comment by dylancom** [comment]
The default, arm64 and arm7.

**Comment by sbooth** [comment]
I believe iOS 10 is the maximum deployment target for 32-bit targets.

**Comment by sbooth** [comment]
You could probably change the iOS deployment target and get a 32-bit build, but I haven't tried.

**Comment by dylancom** [comment]
Changing the deployment target from 14.0 to 10.0 worked perfectly. Thanks!

**Comment by sbooth** [comment]
I need to add a README to the repo to document this explicitly but this project builds the taglib2 branch since that is what I use in `SFBAudioEngine`.

**Comment by dylancom** [comment]
Only running on a real device in debug mode results in an error: `building for iOS, but linking in dylib file (**/Build/Products/Debug-iphoneos/taglib.framework/taglib) built for iOS Simulator, file '**/Build/Products/Debug-iphoneos/taglib.framework/taglib' for architecture arm64`.
When changing the Build Configuration to Release, it works.
