### ISSUE TITLE
Errors with fishsound

### ISSUE THREAD

**Issue by fig7** [sbooth/AudioXCFrameworks#74]
I had two problems building the AudioXCFrameworks.

1. flac.c didn't build. This was an easy fix, size_t isn't the same as an unsigned int anymore. (See attached patch)
2. Even after the build was fixed, it still wouldn't create the framework (from the xcodebuild -create-xcframework step):
error: the path does not point to a valid framework

I tried to investigate a bit, but I couldn't figure it out. Alas, I am not an expert with makefiles.
Maybe it has something to do with the fact that fishsound appears to include some of the other frameworks? I don't know.
[fishsound.patch](https://github.com/sbooth/AudioXCFrameworks/files/15335782/fishsound.patch)

**Comment by sbooth** [comment]
Thanks for the patch. The compilation problems are fixed in #75 

I'm not sure what the framework creation problem could be. I tried `make clean` followed by `make` at the top level and all of the XCFrameworks built correctly. What versions of macOS and Xcode are you using?

**Comment by fig7** [comment]
I'm on 14.4.1 and 15.3 (on a Mac M1 mini). In any case, I don't need fishsound, so the workaround is to just remove it for now.
